language: ruby
before_install:
  - cp ci/Gemfile.ci Gemfile.ci
  - export BUNDLE_GEMFILE=$PWD/Gemfile.ci
bundler_args: --without debug
rvm:
  - 1.9.3
  - 2.0.0
env:
  - DB=mysql
  - DB=postgresql
  - DB=sqlite
before_script:
  - sqlite3 --version
  - mysql --version
  - mysql -e 'create database ocw_test;'
  - psql --version
  - psql -c 'create database ocw_test;' -U postgres
  - ruby ci/copy_database_config.rb
  - bundle exec rake db:migrate
