language: ruby
before_install: cp Gemfile.lock ci/Gemfile.ci.lock
gemfile: ci/Gemfile.ci
bundler_args: --without development
rvm:
  - 1.8.7
  - ree
  - 1.9.3
  - 2.0.0
env:
  - DB=mysql
  - DB=postgresql
  - DB=sqlite
before_script:
  - mysql -e 'create database ocw_test;'
  - psql -c 'create database ocw_test;' -U postgres
  - ruby ci/copy_database_config.rb
  - bundle exec rake db:migrate
