#===[ Secrets ]=========================================================
#
# This file is meant for storing secret information that is never
# published or committed to a revision control system.
#
#---[ Values ]----------------------------------------------------------

# Email address of administrator that will get requests for assistance from users:
administrator_email: 'your@email.addr'

# Secret key for getting an ATOM feed of private comments:
comments_secret: e7ed7cc63ae64f10fcb1dd9c7ba34656242dca9642222dcdaa8bd63a074913d9edbe300b0bef6bdc24e9a4cf7ad3f3177c6a762a8b62ad5ca482570d3969b19b

# The Rails secret_key_base
# Used by config/initializers/secret_token.rb
secret_key_base: 1f5085ba0fbf858fa957a9ea1406898266b8685a51da9b2127afcd8d2e54ba454a51cd59d39265e1819144da15594874dcb5a8bbfd2a5f3bcc7d30960619bb94

#===[ fin ]=============================================================
