# Install the MySQL driver:
#   gem install mysql2

common: &common
  adapter: mysql2
  encoding: utf8
  socket: <%= `mysql_config --socket`.chomp %>
  username: <%= `whoami`.chomp %>
  password:

development:
  database: ocw_dev
  << : *common

preview:
  database: ocw_dev
  << : *common

test: &test
  database: ocw_test
  << : *common

cucumber:
  <<: *test

production:
  database: ocw_prod
  << : *common
