<%
# database.yml customizer
# =======================
#
# Load database configuration from this custom file if it exists:
custom  = "#{Rails.root}/config/database~custom.yml"
# ...otherwise, load database configuration from this default file:
default = "#{Rails.root}/config/database~sqlite3.sample.yml"
%>
<%= ERB.new(File.read(File.exist?(custom) ? custom : default)).result() %>
